"""create awards table

Revision ID: 067a8b3c7785
Revises: 9932124a6444
Create Date: 2026-02-21 01:52:14.923961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067a8b3c7785'
down_revision: Union[str, Sequence[str], None] = '9932124a6444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('organization', sa.String(), nullable=False))
    op.alter_column('awards', 'award_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('awards', 'category')
    op.drop_column('awards', 'awarding_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('awarding_body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('awards', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('awards', 'award_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('awards', 'organization')
    # ### end Alembic commands ###
