"""add duration to projects

Revision ID: 107f3a46213d
Revises: 8660cde1a7f2
Create Date: 2026-02-20 01:27:17.348708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107f3a46213d'
down_revision: Union[str, Sequence[str], None] = '8660cde1a7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('duration', sa.String(), nullable=True))
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'funding_agency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'currency')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('projects', 'funding_agency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('projects', 'duration')
    # ### end Alembic commands ###
