"""add publications table

Revision ID: 2a22674dc1fc
Revises: ff5fa5e7bf13
Create Date: 2026-02-20 00:06:00.780839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a22674dc1fc'
down_revision: Union[str, Sequence[str], None] = 'ff5fa5e7bf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('publication_type', sa.String(), nullable=False),
    sa.Column('journal_name', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('pages', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('is_scopus_indexed', sa.Boolean(), nullable=True),
    sa.Column('is_web_of_science', sa.Boolean(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_index(op.f('ix_publications_year'), 'publications', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_year'), table_name='publications')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
