"""add gallery table

Revision ID: 6feb6a3ced54
Revises: 5a358da8bae4
Create Date: 2026-02-23 14:17:40.564182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6feb6a3ced54'
down_revision: Union[str, Sequence[str], None] = '5a358da8bae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('title', sa.String(), nullable=False))
    op.add_column('gallery', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('gallery', sa.Column('media_url', sa.String(), nullable=False))
    op.add_column('gallery', sa.Column('media_type', sa.String(), nullable=False))
    op.add_column('gallery', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('gallery_faculty_id_fkey'), 'gallery', type_='foreignkey')
    op.drop_column('gallery', 'caption')
    op.drop_column('gallery', 'image_url')
    op.drop_column('gallery', 'category')
    op.drop_column('gallery', 'uploaded_at')
    op.drop_column('gallery', 'faculty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gallery', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gallery', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gallery', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gallery', sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gallery_faculty_id_fkey'), 'gallery', 'faculty', ['faculty_id'], ['id'])
    op.drop_column('gallery', 'created_at')
    op.drop_column('gallery', 'media_type')
    op.drop_column('gallery', 'media_url')
    op.drop_column('gallery', 'description')
    op.drop_column('gallery', 'title')
    # ### end Alembic commands ###
