"""add phd_students table

Revision ID: 81440c845fb4
Revises: 5667ed8ce9c3
Create Date: 2026-02-20 00:15:56.002809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81440c845fb4'
down_revision: Union[str, Sequence[str], None] = '5667ed8ce9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phd_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('thesis_title', sa.Text(), nullable=False),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phd_students_id'), 'phd_students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phd_students_id'), table_name='phd_students')
    op.drop_table('phd_students')
    # ### end Alembic commands ###
