"""add phd profile image and bio

Revision ID: 8b87b5a95fb4
Revises: 9067def11c04
Create Date: 2026-02-21 23:10:31.066008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b87b5a95fb4'
down_revision: Union[str, Sequence[str], None] = '9067def11c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phd_students', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('phd_students', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('phd_students', sa.Column('research_area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phd_students', 'research_area')
    op.drop_column('phd_students', 'bio')
    op.drop_column('phd_students', 'profile_image')
    # ### end Alembic commands ###
