"""create patents table

Revision ID: 9067def11c04
Revises: e0617ea9a1f8
Create Date: 2026-02-21 03:09:45.087837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9067def11c04'
down_revision: Union[str, Sequence[str], None] = 'e0617ea9a1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_patent_type_status', 'patents', ['patent_type', 'status'], unique=False)
    op.create_index(op.f('ix_patents_application_number'), 'patents', ['application_number'], unique=False)
    op.create_index(op.f('ix_patents_faculty_id'), 'patents', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_patents_patent_type'), 'patents', ['patent_type'], unique=False)
    op.create_index(op.f('ix_patents_registration_number'), 'patents', ['registration_number'], unique=False)
    op.create_index(op.f('ix_patents_status'), 'patents', ['status'], unique=False)
    op.create_index(op.f('ix_publications_faculty_id'), 'publications', ['faculty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_faculty_id'), table_name='publications')
    op.drop_index(op.f('ix_patents_status'), table_name='patents')
    op.drop_index(op.f('ix_patents_registration_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_patent_type'), table_name='patents')
    op.drop_index(op.f('ix_patents_faculty_id'), table_name='patents')
    op.drop_index(op.f('ix_patents_application_number'), table_name='patents')
    op.drop_index('ix_patent_type_status', table_name='patents')
    # ### end Alembic commands ###
