"""add official_url to books

Revision ID: 958ddddb9857
Revises: f1b547f5242d
Create Date: 2026-02-22 18:05:44.716770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958ddddb9857'
down_revision: Union[str, Sequence[str], None] = 'f1b547f5242d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('official_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'official_url')
    # ### end Alembic commands ###
