"""add book category enum

Revision ID: 9932124a6444
Revises: d4f2767432a6
Create Date: 2026-02-20 01:46:39.542166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9932124a6444'
down_revision: Union[str, Sequence[str], None] = 'd4f2767432a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('year', sa.Integer(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('books', 'book_type')
    op.drop_column('books', 'description')
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('book_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('books', 'year')
    # ### end Alembic commands ###
