"""add profile_image to faculty

Revision ID: e2cebda31515
Revises: 8b87b5a95fb4
Create Date: 2026-02-22 16:54:28.840756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cebda31515'
down_revision: Union[str, Sequence[str], None] = '8b87b5a95fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'profile_image')
    # ### end Alembic commands ###
