"""add publication enhancements

Revision ID: f1b547f5242d
Revises: e2cebda31515
Create Date: 2026-02-22 17:23:02.929263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b547f5242d'
down_revision: Union[str, Sequence[str], None] = 'e2cebda31515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('official_url', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('abstract', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'abstract')
    op.drop_column('publications', 'cover_image')
    op.drop_column('publications', 'official_url')
    # ### end Alembic commands ###
