from .user import User
from .faculty import Faculty
from .publication import Publication
from .project import Project
from .phd_student import PhDStudent
from .patent import Patent
from .award import Award
from .book import Book
from .invited_lecture import InvitedLecture
from .gallery import Gallery
